### ISSUE TITLE
Prepare step overrides config.xml

### ISSUE THREAD

**Issue by bayssmekanique** [bitrise-community/steps-cordova-archive#10]
Part of the _Preparing project_ (`main.go:476`) logic performs a `platform rm` on each platform, which causes the platform settings in `config.xml` and `package.json` to be cleared.  This results in the engine targets being cleared and not applied during the `platform add` process.

Part of the solution to #9 involves specifying the `cordova-ios` version in the `config.xml`, but it gets immediately over-written and I do not see an existing solution.

I'm willing to submit a PR to resolve the issue, but I'm not confident in Go.  I'm also not certain if it's best to add a configuration for disabling the `platform rm` portion or to add overrides for the engine values (similar to how Cordova version is handled).

**Comment by godrei** [comment]
Hi @bayssmekanique ,
thanks for the issue report and for the detailed explanation!
I agree with adding a new input like: `readd_platform` and PR would be well appreciated!
