### ISSUE TITLE
Add a option to skip platform add

### ISSUE THREAD

**Issue by Tallyb** [bitrise-community/steps-cordova-archive#26]
similar to platform remove. Should be able to bypass platform add. 
Starting cordova 8.1.0 if the platform exists, this is caught as an error

**Comment by trapacska** [comment]
Hey @Tallyb !

Is the input `readd_platform` does the same you are about? Could you please provide more info and use-case?

**Comment by bayssmekanique** [comment]
`readd_platform` allows you to bypass the platform removal, but it will still run the platform add command.

https://github.com/bitrise-community/steps-cordova-archive/blob/5625552ad051b91f58963d3795b047a228cdb0a6/main.go#L301-L315

Settings `readd_platform` to `true` would cause it to wipe out the platform and then re-add the platform back in which should resolve your issue.  Having worked with cordova in a CI environment for a few years now, you are typically better off to destroy and rebuild the platforms directories each time.

**Comment by xavier-villelegier** [comment]
I agree that this would be a nice input for this step. If you need to run custom logic after the platform add, you usually use a custom script just before the cordova archive step, and you don't need to re-add it. It worked with Cordova 8.0 because the error was not blocking the step (just an "ios platform already added" message), but with the latest Cordova it just stops the step.

As a workaround I use the same command that the step uses in a custom script (depending on the config of course)
```
cordova compile --release --device ios
```

**Comment by Tallyb** [comment]
@xavier-villelegier  - I agree that the script is a workaround, but then why we have steps? 

@bayssmekanique  - I agree that clean platform is the key for the build. It is just that the platform is added on the cordova prepare - just 2 steps before that....

**Comment by BirmacherAkos** [comment]
Hi!

Thanks for the idea. 🥇 

I have created a card for the Tooling Team and they will check the possible options.

**Comment by bayssmekanique** [comment]
@BirmacherAkos, can you guys take a look at #27.  I think it failed the check due to the GH outage yesterday.

**Comment by trapacska** [comment]
@bayssmekanique what do you think, why is it important to keep the re-add functionality? So `prepare` can't just swap it?

**Comment by bayssmekanique** [comment]
@trapacska, at this point I feel like it's necessary for backwards compatibility.  Older versions of Cordova acted differently (hints why this call exists in the first place), so I'm fearful to remove it for that reason alone. If it is removed, I would say it needs to be a major version bump, and there's probably quite a few other things that would need to go along with it.

**Comment by Tallyb** [comment]
Until this is merged - my repo has the PR included: https://github.com/Tallyb/steps-cordova-archive. 
You can use it in the bitrise.yml as 
`- git::https://github.com/Tallyb/steps-cordova-archive.git:` (instead of - cordova-archive). 
Don't forget to add input ` - add_platform: 'false'`

**Comment by trapacska** [comment]
The PR is just merged and a new version is released: https://github.com/bitrise-community/steps-cordova-archive/releases/tag/1.2.0

Thanks!

Closing the issue but feel free to re-open if you encounter any issues with it.
