### ISSUE TITLE
Cordova config.xml / package.json

### ISSUE THREAD

**Issue by TMC-LLB** [bitrise-community/steps-cordova-archive#35]
When building a project, if there is a package.json that contains dependencies for any cordova plugins the prepare fails, it seems to get confused when loading plugins?

If I remove the dependencies for any plugins from package.json it works and installs everything using just the config.xml. 

I've created a public project to show this:

**Failing: With plugin dependencies in package.json:**
https://app.bitrise.io/build/6455e8dfb1068010

**Working: With no plugins in dependencies package.json**
https://app.bitrise.io/build/0243e13b969eb553

**Comment by bayssmekanique** [comment]
I believe this is an issue with Cordova, not this plugin specifically.

**Comment by fehersanyi-bitrise** [comment]
Hello @TMC-LLB 

Could you try running the archive with cordova version 7.0.1?
based on this thread: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/922
You can set it here: 
<img width="259" alt="Screenshot 2019-03-12 at 14 57 46" src="https://user-images.githubusercontent.com/43136024/54205782-49e65500-44d7-11e9-9e02-8f045ef7966b.png">
in the cordova archive step

**Comment by TMC-LLB** [comment]
Hi @fehersanyi-bitrise,

I did manage to get it to work with 8.  The problem was what was reported in the social sharing plugin, I had to update to the latest version.

It also affected another other plugin (cordova-plugin-code-push) which was also solved by updating to the latest version.

The cordova cli doesn't have very sensible output when there is a failure of a hard dependency.
