### ISSUE TITLE
Failing during archive on XCode9

### ISSUE THREAD

**Issue by bayssmekanique** [bitrise-community/steps-cordova-archive#9]
Fails with message: 
>Error Domain=IDEProvisioningErrorDomain Code=9 ""MyApp.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="Metrics.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

BitRise Blog identified the issue and has a potential fix: https://blog.bitrise.io/new-export-options-plist-in-xcode-9

**Comment by bayssmekanique** [comment]
This actually appears to be an issue with `cordova-ios`.

https://github.com/apache/cordova-ios/pull/338

**Comment by viktorbenei** [comment]
Thanks for reporting & for the link @bayssmekanique ! :)
